Vagrant.configure("2") do |config|

  config.vm.define "mysql-server" do |cfg|
    cfg.vm.box =  "javacommons/ubuntu-20.04-mysql-8.0"
	cfg.vm.box_version = "1.0"
    #cfg.vbguest.installer_options = { allow_kernel_upgrade: true }
    cfg.vm.provider "virtualbox" do |vb|
	  vb.name = "mysql-server"
 	  vb.gui = true
      vb.cpus = "1"
      vb.memory = "2048"
    end
	cfg.vm.host_name = "mysql-server"
    cfg.vm.network "private_network", ip: "192.168.1.21"
    cfg.vm.network "forwarded_port", guest: 22, host: 60021, auto_correct: true, id: "ssh"
    # cfg.vm.network "forwarded_port", guest: 3306, host: 3336, ip: "127.0.0.1", auto_correct: false, id: "ssh"
    cfg.vm.provision "shell", inline: "apt-get update"
    cfg.vm.provision "shell", path: "bash_ssh_conf_4_CentOS.sh"
    cfg.vm.provision "file", source: "board.sql", destination: "board.sql"
    cfg.vm.provision "shell", inline: "sudo mysql -u root < board.sql"
  end  
  
    config.vm.define "tomcat-node01" do |cfg|
    cfg.vm.box = "bento/ubuntu-20.04"
	#cfg.vm.box_version = "2404.23.0"
	#cfg.vbguest.installer_options = { allow_kernel_upgrade: true }
	cfg.vm.provider "virtualbox" do |vb|
	  vb.name = "tomcat-node01"
 	  vb.gui = true
      vb.cpus = "1"
      vb.memory = "2048"
    end
	cfg.vm.host_name = "tomcat-node01"
    cfg.vm.network "private_network", ip: "192.168.1.22"
    cfg.vm.network "forwarded_port", guest: 22, host: 60022, auto_correct: true, id: "ssh"
	#cfg.vm.network "forwarded_port", guest: 3306, host: 3306, ip: "127.0.0.1", auto_correct: false, id: "ssh"
    cfg.vm.provision "shell", inline: "apt-get update"
    cfg.vm.provision "shell", path: "scripts/tomcat.sh"
	
  end

    config.vm.define "tomcat-node02" do |cfg|
    cfg.vm.box = "bento/ubuntu-20.04"
	#cfg.vm.box_version = "2404.23.0"
	cfg.vm.provider "virtualbox" do |vb|
	  vb.name = "tomcat-node02"
 	  vb.gui = true
      vb.cpus = "1"
      vb.memory = "2048"
    end
	cfg.vm.host_name = "tomcat-node02"
    cfg.vm.network "private_network", ip: "192.168.1.23"
    cfg.vm.network "forwarded_port", guest: 22, host: 60023, auto_correct: true, id: "ssh"
	#cfg.vm.network "forwarded_port", guest: 3306, host: 3306, ip: "127.0.0.1", auto_correct: false, id: "ssh"
    cfg.vm.provision "shell", inline: "apt-get update"
    cfg.vm.provision "shell", path: "scripts/tomcat.sh"
	
  end
  
    config.vm.define "nginx-node01" do |cfg|
    cfg.vm.box = "bento/ubuntu-20.04"
	#cfg.vm.box_version = "2404.23.0"
	cfg.vm.provider "virtualbox" do |vb|
	  vb.name = "nginx-node01"
 	  vb.gui = true
      vb.cpus = "1"
      vb.memory = "2048"
    end
	cfg.vm.host_name = "nginx-node01"
    cfg.vm.network "private_network", ip: "192.168.1.30"
    cfg.vm.network "forwarded_port", guest: 22, host: 60023, auto_correct: true, id: "ssh"
	#cfg.vm.network "forwarded_port", guest: 3306, host: 3306, ip: "127.0.0.1", auto_correct: false, id: "ssh"
    cfg.vm.provision "shell", inline: "apt-get update"
    cfg.vm.provision "shell", inline: "apt-get install -y nginx"
    cfg.vm.provision "shell", inline: "systemctl start nginx"
	cfg.vm.provision "shell", inline: "systemctl status nginx"

    # Configure nginx to serve the JSP project
    cfg.vm.provision "shell", path: "scripts/nginx.sh"
	
  end
  
	
end