apiVersion: v1
data:
  DB_Password: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: null
  name: db-secret
--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv 
spec:
  volumeMode: Filesystem
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
   path: /mysql/mysql_data
  claimRef:
   name: mysql-pvc
   namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
  storageClassName: ""
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
#  type: LoadBalancer
  clusterIP: 172.17.30.100
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30300